name: Issues-workflow
on: issues
jobs:
  Output-version:
    runs-on: ubuntu-latest
    steps:
      - name: output the events
        run: echo " ${{(github.run_number)}}"
  Output-events:
    needs: Output-version
    runs-on: ubuntu-latest
    steps:
      - name: output the events
        run: echo " ${{(github.event)}}"