name: Issues-workflow
on: 
  pull_request: [opened,edited]
  workflow_dispatch:
jobs:
  Output-version:
    runs-on: ubuntu-latest
    steps:
      - name: output the events
        run: echo " ${{(github.run_number)}}"
  Output-events:
    needs: Output-version
    runs-on: ubuntu-latest
    steps:
      - name: output the events
        run: echo " ${{toJSON(github.event)}}"