name: workflow1name
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
      - uses: actions/checkout@v3
      - name: Install dependencies
      - run: npm ci
      - name: build the code
      - run: npm run build
  Lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
      - uses: actions/checkout@v3
      - name: Install dependencies
      - run: npm ci
      - name: Run lint
      - run: npm run lint
  Test:
    runs-on: ubuntu-latest
    needs: [build,Lint]
    steps:
      - name: Get Code
      - uses: actions/checkout@v3
      - name: Install dependencies
      - run: npm ci
      - name: Testing 
      - run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    needs: [build,Lint,Test]
    steps:
      - name: Get Code
      - uses: actions/checkout@v3
      - name: Deploy
      - run: echo "Deploying..."
  